# Generated by Django 3.1 on 2020-08-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_activity_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='username',
            field=models.CharField(max_length=20),
        ),
    ]
