# Generated by Django 3.1 on 2020-09-03 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_auto_20200903_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='create_date',
            field=models.DateTimeField(),
        ),
    ]
