# Generated by Django 3.1 on 2020-09-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_auto_20200903_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='completed',
            field=models.CharField(default='yes', max_length=3),
            preserve_default=False,
        ),
    ]
